[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'kaicataldo/material.vim'
hook_add = '''exec 'source ' . g:rc_dir . '/material_vim.vim' '''

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''exec 'source ' . g:rc_dir . '/indentLine.vim' '''

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'airblade/vim-gitgutter'
if = '''executable('git')'''
hook_add = '''exec 'source ' . g:rc_dir . '/vim-gitgutter.vim' '''

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'dag/vim-fish'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''exec 'source ' . g:rc_dir . '/vim-airline.vim' '''
depends = ['material']

[[plugins]]
repo = 'tpope/vim-fugitive'
if = '''executable('git')'''

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
depends = ['nerdtree']

[[plugins]]
repo = 'keith/swift.vim'
hook_add = '''exec 'source ' . g:rc_dir . '/swift_vim.vim' '''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''exec 'source ' . g:rc_dir . '/nerdtree.vim' '''

[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_add = '''exec 'source ' . g:rc_dir . '/tcomment_vim.vim' '''

[[plugins]]
repo = 'chiphogg/vim-prototxt'

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''exec 'source ' . g:rc_dir . '/rainbow.vim' '''

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
bulid = 'bash install.sh'
hook_add = '''exec 'source ' . g:rc_dir . '/LanguageClient-neovim.vim' '''

[[plugins]]
repo = 'junegunn/fzf'
depends = ['LanguageClient-neovim']
