[[plugins]]
repo  = 'mattn/emmet-vim'
on_ft = ['html', 'css', 'sass', 'php']
on_i = 1

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = ['python']
on_i = 1

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = '''executable('python3') && has('python3')'''
on_i = 1
hook_source = '''exec 'source ' . g:rc_dir . '/deoplete_nvim.vim' '''

[[plugins]]
repo = 'roxma/nvim-yarp'
if = '''!has('nvim') && executable('python3') && has('python3')'''
on_i = 1

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = '''!has('nvim') && executable('python3') && has('python3')'''
on_i = 1
