[[plugins]]
repo  = 'mattn/emmet-vim'
on_ft = ['html', 'css', 'sass', 'php']
on_i = 1

[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = ['deoplete.nvim']
on_ft = ['python']
on_i = 1

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = ['python']
on_i = 1

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = ['nvim-yarp', 'vim-hug-neovim-rpc']
hook_source = '''
    let g:deoplete#enable_at_startup = 1

    if filereadable('/usr/bin/python3')
        let g:python3_host_prog = '/usr/bin/python3'
    elseif filereadable('/usr/local/bin/python3')
        let g:python3_host_prog = '/usr/local/bin/python3'
    else
        let g:python3_host_prog = '/usr/bin/env python3'
    endif
'''
on_i = 1

[[plugins]]
repo = 'roxma/nvim-yarp'
if = '''!has('nvim')'''
on_i = 1

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = '''!has('nvim')'''
on_i = 1

[[plugins]]
repo = 'Shougo/neco-vim'
depends = ['deoplete.nvim']
on_i = 1

[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = 'rust'
on_i = 1
hook_source = '''
    set hidden
    let g:racer_experimental_completer = 1
    au FileType rust nmap gd <Plug>(rust-def)
    au FileType rust nmap gs <Plug>(rust-def-split)
    au FileType rust nmap gx <Plug>(rust-def-vertical)
    au FileType rust nmap <leader>gd <Plug>(rust-doc)
'''

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
