[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'kaicataldo/material.vim'
hook_add = '''
    if has('termguicolors')
        set termguicolors
    endif

    " 24-bit color
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

    set background=dark
    colorscheme material
    let g:material_theme_style = 'dark'

    let g:airline_theme = 'material'
'''

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
    let g:indentLine_leadingSpaceEnabled = 1
    let g:indentLine_leadingSpaceChar = '·'
'''

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'airblade/vim-gitgutter'
if = '''executable('git')'''
hook_add = '''
    if executable('rg')
        let g:gitgutter_grep = 'rg'
    endif
    set updatetime=100
'''

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'dag/vim-fish'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
    set laststatus=2
    let g:airline#extensions#tabline#enabled = 1
    let g:airline_powerline_fonts = 1
    let g:airline_skip_empty_sections = 1
'''
depends = ['material']

[[plugins]]
repo = 'tpope/vim-fugitive'
if = '''executable('git')'''

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
depends = ['nerdtree']

[[plugins]]
repo = 'keith/swift.vim'
hook_add = '''let g:syntastic_swift_checkers = ['swiftpm', 'swiftlint']'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'let g:NERDTreeShowHidden = 1'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'chiphogg/vim-prototxt'

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = 'let g:rainbow_active = 1'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
depends = 'nerdtree'
hook_add = '''
    map <Leader>n <plug>NERDTreeTabsTogglee<CR>
    let g:nerdtree_tabs_open_on_console_startup = 1
    let g:nerdtree_tabs_autofind = 1
'''

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
bulid = 'bash install.sh'
hook_add = '''
    set hidden
    set signcolumn=yes

    let g:LanguageClient_serverCommands = {}
    if executable('rls')
        let g:LanguageClient_serverCommands['rust'] = ['~/.cargo/bin/rustup', 'run', 'nightly', 'rls']
    endif
    if executable('pyls')
        let g:LanguageClient_serverCommands['python'] = ['/usr/local/bin/pyls']
    endif
    if executable('/usr/local/opt/llvm/bin/clangd')
        let g:LanguageClient_serverCommands['c'] = ['/usr/local/opt/llvm/bin/clangd']
        let g:LanguageClient_serverCommands['cpp'] = ['/usr/local/opt/llvm/bin/clangd']
    endif

    nnoremap <silent> K :call LanguageClient#textDocument_hover()<CR>
    nnoremap <silent> gd :call LanguageClient#textDocument_definition({'gotoCmd': 'split'})<CR>
    nnoremap <silent> <F2> :call LanguageClient#textDocument_rename()<CR>
    nnoremap <F3> :call LanguageClient_textDocument_references()<CR>
    nnoremap <F5> :call LanguageClient_contextMenu()<CR>
'''

[[plugins]]
repo = 'junegunn/fzf'
depends = ['LanguageClient-neovim']
