[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'kaicataldo/material.vim'
hook_add = 'source material_vim.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = 'source indnetLine.vim'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'airblade/vim-gitgutter'
if = '''executable('git')'''
hook_add = 'source vim-gitgutter.vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'dag/vim-fish'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = 'source vim-airline.vim'
depends = ['material']

[[plugins]]
repo = 'tpope/vim-fugitive'
if = '''executable('git')'''

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
depends = ['nerdtree']

[[plugins]]
repo = 'keith/swift.vim'
hook_add = 'source swift_vim.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'source nerdtree.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_add = 'source tcomment_vim.vim'

[[plugins]]
repo = 'chiphogg/vim-prototxt'

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = 'source rainbow.vim'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
bulid = 'bash install.sh'
hook_add = 'source LanguageClient-neovim'

[[plugins]]
repo = 'junegunn/fzf'
depends = ['LanguageClient-neovim']
