[general]
import = [
    "~/.config/alacritty/themes/themes/papercolor_dark.toml"
]

[terminal]
shell = { program = "/opt/homebrew/bin/tmux", args = ["new", "-As", "main"] }

[font]
normal = { family = "SFMono Nerd Font", style = "Regular" }
size = 12

[window]
dimensions = { columns = 140, lines = 48 }

[selection]
save_to_clipboard = true
